// @ts-check


const packagesToCheck = [
    "embeddable-components",
    "editor"
]

/** @type {import('typedoc').TypeDocOptions & import('typedoc-plugin-markdown').PluginOptions} */
module.exports = {
    entryPoints: [`./packages/{${packagesToCheck.join(",")}}`],
    includeVersion: true,
    out: "docs",
    name: "Uh Little Less Dum",
    plugin: ["typedoc-plugin-markdown", "typedoc-plugin-remark", "typedoc-github-wiki-theme", "typedoc-plugin-coverage", "typedoc-plugin-mdn-links", "typedoc-plugin-zod", "typedoc-plugin-include-example", "@droppedcode/typedoc-plugin-relative-includes", "typedoc-plugin-frontmatter", "./typedoc/navigation.cjs", "./typedoc/customFrontMatter.cjs"],
    includes: ["typedocIncludes"],
    outputFileStrategy: "modules",
    githubPages: false,
    fileExtension: ".mdx",
    readme: "./README.md",
    mergeReadme: true,
    publicPath: "/",
    expandObjects: true,
    expandParameters: true,
    parametersFormat: "table", // "table" | "list"
    propertiesFormat: "table", // "table" | "list"
    enumMembersFormat: "list", // "table" | "list"
    useCodeBlocks: true,
    textContentMappings: {
        "breadcrumbs.home": "Home",
        // "header.title": "{projectName} {version}",
        // "header.docs": "Docs",
        // "breadcrumbs.home": "{projectName} {version}",
        // "footer.text": "",
        // "title.indexPage": "{projectName} {version}",
        // "title.modulePage": "{name}",
        // "title.memberPage": "{kind}: {name}",
        // "label.apiIndex": "API Index",
        // "label.defaultValue": "Default value",
        // "label.description": "Description",
        // "label.extendedBy": "Extended by",
        // "label.extends": "Extends",
        // "label.flags": "Flags",
        // "label.globals": "Globals",
        // "label.implements": "Implements",
        // "label.implementationOf": "Implementation of",
        // "label.inheritedFrom": "Inherited from",
        // "label.index": "Index",
        // "label.indexable": "Indexable",
        // "label.indexSignature": "Index signature",
        // "label.member": "Member",
        // "label.modifier": "Modifier",
        // "label.name": "Name",
        // "label.overrides": "Overrides",
        // "label.packages": "Packages",
        // "label.reExports": "Re-exports",
        // "label.renamesAndReExports": "Renames and re-exports",
        // "label.returns": "Returns",
        // "label.source": "Source",
        // "label.type": "Type",
        // "label.typeDeclaration": "Type declaration",
        // "label.value": "Value",
        // "kind.accessor.singular": "Accessor",
        // "kind.accessor.plural": "Accessors",
        // "kind.class.singular": "Class",
        // "kind.class.plural": "Classes",
        // "kind.constructor.singular": "Constructor",
        // "kind.constructor.plural": "Constructors",
        // "kind.enum.singular": "Enumeration",
        // "kind.enum.plural": "Enumerations",
        // "kind.enumMember.singular": "Enumeration Member",
        // "kind.enumMember.plural": "Enumeration Members",
        // "kind.event.singular": "Event",
        // "kind.event.plural": "Events",
        // "kind.function.singular": "Function",
        // "kind.function.plural": "Functions",
        // "kind.interface.singular": "Interface",
        // "kind.interface.plural": "Interfaces",
        // "kind.method.singular": "Method",
        // "kind.method.plural": "Methods",
        // "kind.module.singular": "Module",
        // "kind.module.plural": "Modules",
        // "kind.namespace.singular": "Namespace",
        // "kind.namespace.plural": "Namespaces",
        // "kind.variable.singular": "Variable",
        // "kind.variable.plural": "Variables",
        // "kind.parameter.singular": "Parameter",
        // "kind.parameter.plural": "Parameters",
        // "kind.property.singular": "Property",
        // "kind.property.plural": "Properties",
        // "kind.reference.singular": "Reference",
        // "kind.reference.plural": "References",
        // "kind.typeAlias.singular": "Type alias",
        // "kind.typeAlias.plural": "Type Aliases",
        // "kind.typeParameter.singular": "Type parameter",
        // "kind.typeParameter.plural": "Type parameters"
    },
    remarkPlugins: [
        "remark-math",
        "remark-gfm",
        "remark-emoji",
        [
            "remark-github",
            { "repository": "https://github.com/igloo1505/ulld" }
        ],
    ]
}
