export type {
    SlotMap,
    ComponentConfig,
    EmbeddableConfig,
    DeveloperConfigInput,
    ParserConfig,
    AdditionalImportsConfig,
    TrpcConfig,
    PluginSettingsConfig,
    PluginPageConfig,
    PluginEventsConfig,
} from "@ulld/configschema/developerTypes";

export type {
    ErrorMarginProps,
    AbstractProps,
    EmbeddableCardProps,
    EmbeddedImageProps,
    GridProps,
    GridItemProps,
    TabGroupProps,
    VideoProps,
    ModelViewProps,
    TitleProps,
    WithTooltipWrapper,
    VSpaceProps,
    UnderlineProps,
    SmallProps,
    CenteredTextProps,
    LargeProps,
    LeadTextProps,
    QuoteProps,
    EquationRefProps,
    HighlightProps,
    AdmonitionProps
} from "@ulld/embeddable-components/propTypes";
