import physics from "#/staticData/physicalConstants.json";
import { Numpy } from "./Numpy";

export type PhysicalConstant = "c" | "g" | "G" | keyof typeof physics

type T = {
    [k in keyof typeof physics]: number | undefined;
};

export class PhysicalConstants extends Numpy implements T {
    c: number;
    g: number;
    G: number;
    "Wien displacement law constant": number | undefined = undefined;
    "atomic unit of 1st hyperpolarizablity": number | undefined = undefined;
    "atomic unit of 2nd hyperpolarizablity": number | undefined = undefined;
    "atomic unit of electric dipole moment": number | undefined = undefined;
    "atomic unit of electric polarizablity": number | undefined = undefined;
    "atomic unit of electric quadrupole moment": number | undefined = undefined;
    "atomic unit of magn. dipole moment": number | undefined = undefined;
    "atomic unit of magn. flux density": number | undefined = undefined;
    "deuteron magn. moment": number | undefined = undefined;
    "deuteron magn. moment to Bohr magneton ratio": number | undefined =
        undefined;
    "deuteron magn. moment to nuclear magneton ratio": number | undefined =
        undefined;
    "deuteron-electron magn. moment ratio": number | undefined = undefined;
    "deuteron-proton magn. moment ratio": number | undefined = undefined;
    "deuteron-neutron magn. moment ratio": number | undefined = undefined;
    "electron gyromagn. ratio": number | undefined = undefined;
    "electron gyromagn. ratio over 2 pi": number | undefined = undefined;
    "electron magn. moment": number | undefined = undefined;
    "electron magn. moment to Bohr magneton ratio": number | undefined =
        undefined;
    "electron magn. moment to nuclear magneton ratio": number | undefined =
        undefined;
    "electron magn. moment anomaly": number | undefined = undefined;
    "electron to shielded proton magn. moment ratio": number | undefined =
        undefined;
    "electron to shielded helion magn. moment ratio": number | undefined =
        undefined;
    "electron-deuteron magn. moment ratio": number | undefined = undefined;
    "electron-muon magn. moment ratio": number | undefined = undefined;
    "electron-neutron magn. moment ratio": number | undefined = undefined;
    "electron-proton magn. moment ratio": number | undefined = undefined;
    "magn. constant": number | undefined = undefined;
    "magn. flux quantum": number | undefined = undefined;
    "muon magn. moment": number | undefined = undefined;
    "muon magn. moment to Bohr magneton ratio": number | undefined = undefined;
    "muon magn. moment to nuclear magneton ratio": number | undefined = undefined;
    "muon-proton magn. moment ratio": number | undefined = undefined;
    "neutron gyromagn. ratio": number | undefined = undefined;
    "neutron gyromagn. ratio over 2 pi": number | undefined = undefined;
    "neutron magn. moment": number | undefined = undefined;
    "neutron magn. moment to Bohr magneton ratio": number | undefined = undefined;
    "neutron magn. moment to nuclear magneton ratio": number | undefined =
        undefined;
    "neutron to shielded proton magn. moment ratio": number | undefined =
        undefined;
    "neutron-electron magn. moment ratio": number | undefined = undefined;
    "neutron-proton magn. moment ratio": number | undefined = undefined;
    "proton gyromagn. ratio": number | undefined = undefined;
    "proton gyromagn. ratio over 2 pi": number | undefined = undefined;
    "proton magn. moment": number | undefined = undefined;
    "proton magn. moment to Bohr magneton ratio": number | undefined = undefined;
    "proton magn. moment to nuclear magneton ratio": number | undefined =
        undefined;
    "proton magn. shielding correction": number | undefined = undefined;
    "proton-neutron magn. moment ratio": number | undefined = undefined;
    "shielded helion gyromagn. ratio": number | undefined = undefined;
    "shielded helion gyromagn. ratio over 2 pi": number | undefined = undefined;
    "shielded helion magn. moment": number | undefined = undefined;
    "shielded helion magn. moment to Bohr magneton ratio": number | undefined =
        undefined;
    "shielded helion magn. moment to nuclear magneton ratio": number | undefined =
        undefined;
    "shielded helion to proton magn. moment ratio": number | undefined =
        undefined;
    "shielded helion to shielded proton magn. moment ratio": number | undefined =
        undefined;
    "shielded proton magn. moment": number | undefined = undefined;
    "shielded proton magn. moment to Bohr magneton ratio": number | undefined =
        undefined;
    "shielded proton magn. moment to nuclear magneton ratio": number | undefined =
        undefined;
    "{220} lattice spacing of silicon": number | undefined = undefined;
    "lattice spacing of silicon": number | undefined = undefined;
    "alpha particle-electron mass ratio": number | undefined = undefined;
    "alpha particle mass": number | undefined = undefined;
    "alpha particle mass energy equivalent": number | undefined = undefined;
    "alpha particle mass energy equivalent in MeV": number | undefined =
        undefined;
    "alpha particle mass in u": number | undefined = undefined;
    "alpha particle molar mass": number | undefined = undefined;
    "alpha particle-proton mass ratio": number | undefined = undefined;
    "Angstrom star": number | undefined = undefined;
    "atomic mass constant": number | undefined = undefined;
    "atomic mass constant energy equivalent": number | undefined = undefined;
    "atomic mass constant energy equivalent in MeV": number | undefined =
        undefined;
    "atomic mass unit-electron volt relationship": number | undefined = undefined;
    "atomic mass unit-hartree relationship": number | undefined = undefined;
    "atomic mass unit-hertz relationship": number | undefined = undefined;
    "atomic mass unit-inverse meter relationship": number | undefined = undefined;
    "atomic mass unit-joule relationship": number | undefined = undefined;
    "atomic mass unit-kelvin relationship": number | undefined = undefined;
    "atomic mass unit-kilogram relationship": number | undefined = undefined;
    "atomic unit of 1st hyperpolarizability": number | undefined = undefined;
    "atomic unit of 2nd hyperpolarizability": number | undefined = undefined;
    "atomic unit of action": number | undefined = undefined;
    "atomic unit of charge": number | undefined = undefined;
    "atomic unit of charge density": number | undefined = undefined;
    "atomic unit of current": number | undefined = undefined;
    "atomic unit of electric dipole mom.": number | undefined = undefined;
    "atomic unit of electric field": number | undefined = undefined;
    "atomic unit of electric field gradient": number | undefined = undefined;
    "atomic unit of electric polarizability": number | undefined = undefined;
    "atomic unit of electric potential": number | undefined = undefined;
    "atomic unit of electric quadrupole mom.": number | undefined = undefined;
    "atomic unit of energy": number | undefined = undefined;
    "atomic unit of force": number | undefined = undefined;
    "atomic unit of length": number | undefined = undefined;
    "atomic unit of mag. dipole mom.": number | undefined = undefined;
    "atomic unit of mag. flux density": number | undefined = undefined;
    "atomic unit of magnetizability": number | undefined = undefined;
    "atomic unit of mass": number | undefined = undefined;
    "atomic unit of momentum": number | undefined = undefined;
    "atomic unit of permittivity": number | undefined = undefined;
    "atomic unit of time": number | undefined = undefined;
    "atomic unit of velocity": number | undefined = undefined;
    "Avogadro constant": number | undefined = undefined;
    "Bohr magneton": number | undefined = undefined;
    "Bohr magneton in eV/T": number | undefined = undefined;
    "Bohr magneton in Hz/T": number | undefined = undefined;
    "Bohr magneton in inverse meters per tesla": number | undefined = undefined;
    "Bohr magneton in K/T": number | undefined = undefined;
    "Bohr radius": number | undefined = undefined;
    "Boltzmann constant": number | undefined = undefined;
    "Boltzmann constant in eV/K": number | undefined = undefined;
    "Boltzmann constant in Hz/K": number | undefined = undefined;
    "Boltzmann constant in inverse meters per kelvin": number | undefined =
        undefined;
    "characteristic impedance of vacuum": number | undefined = undefined;
    "classical electron radius": number | undefined = undefined;
    "Compton wavelength": number | undefined = undefined;
    "Compton wavelength over 2 pi": number | undefined = undefined;
    "conductance quantum": number | undefined = undefined;
    "conventional value of Josephson constant": number | undefined = undefined;
    "conventional value of von Klitzing constant": number | undefined = undefined;
    "Cu x unit": number | undefined = undefined;
    "deuteron-electron mag. mom. ratio": number | undefined = undefined;
    "deuteron-electron mass ratio": number | undefined = undefined;
    "deuteron g factor": number | undefined = undefined;
    "deuteron mag. mom.": number | undefined = undefined;
    "deuteron mag. mom. to Bohr magneton ratio": number | undefined = undefined;
    "deuteron mag. mom. to nuclear magneton ratio": number | undefined =
        undefined;
    "deuteron mass": number | undefined = undefined;
    "deuteron mass energy equivalent": number | undefined = undefined;
    "deuteron mass energy equivalent in MeV": number | undefined = undefined;
    "deuteron mass in u": number | undefined = undefined;
    "deuteron molar mass": number | undefined = undefined;
    "deuteron-neutron mag. mom. ratio": number | undefined = undefined;
    "deuteron-proton mag. mom. ratio": number | undefined = undefined;
    "deuteron-proton mass ratio": number | undefined = undefined;
    "deuteron rms charge radius": number | undefined = undefined;
    "electric constant": number | undefined = undefined;
    "electron charge to mass quotient": number | undefined = undefined;
    "electron-deuteron mag. mom. ratio": number | undefined = undefined;
    "electron-deuteron mass ratio": number | undefined = undefined;
    "electron g factor": number | undefined = undefined;
    "electron gyromag. ratio": number | undefined = undefined;
    "electron gyromag. ratio over 2 pi": number | undefined = undefined;
    "electron mag. mom.": number | undefined = undefined;
    "electron mag. mom. anomaly": number | undefined = undefined;
    "electron mag. mom. to Bohr magneton ratio": number | undefined = undefined;
    "electron mag. mom. to nuclear magneton ratio": number | undefined =
        undefined;
    "electron mass": number | undefined = undefined;
    "electron mass energy equivalent": number | undefined = undefined;
    "electron mass energy equivalent in MeV": number | undefined = undefined;
    "electron mass in u": number | undefined = undefined;
    "electron molar mass": number | undefined = undefined;
    "electron-muon mag. mom. ratio": number | undefined = undefined;
    "electron-muon mass ratio": number | undefined = undefined;
    "electron-neutron mag. mom. ratio": number | undefined = undefined;
    "electron-neutron mass ratio": number | undefined = undefined;
    "electron-proton mag. mom. ratio": number | undefined = undefined;
    "electron-proton mass ratio": number | undefined = undefined;
    "electron-tau mass ratio": number | undefined = undefined;
    "electron to alpha particle mass ratio": number | undefined = undefined;
    "electron to shielded helion mag. mom. ratio": number | undefined = undefined;
    "electron to shielded proton mag. mom. ratio": number | undefined = undefined;
    "electron volt": number | undefined = undefined;
    "electron volt-atomic mass unit relationship": number | undefined = undefined;
    "electron volt-hartree relationship": number | undefined = undefined;
    "electron volt-hertz relationship": number | undefined = undefined;
    "electron volt-inverse meter relationship": number | undefined = undefined;
    "electron volt-joule relationship": number | undefined = undefined;
    "electron volt-kelvin relationship": number | undefined = undefined;
    "electron volt-kilogram relationship": number | undefined = undefined;
    "elementary charge": number | undefined = undefined;
    "elementary charge over h": number | undefined = undefined;
    "Faraday constant": number | undefined = undefined;
    "Faraday constant for conventional electric current": number | undefined =
        undefined;
    "Fermi coupling constant": number | undefined = undefined;
    "fine-structure constant": number | undefined = undefined;
    "first radiation constant": number | undefined = undefined;
    "first radiation constant for spectral radiance": number | undefined =
        undefined;
    "hartree-atomic mass unit relationship": number | undefined = undefined;
    "hartree-electron volt relationship": number | undefined = undefined;
    "Hartree energy": number | undefined = undefined;
    "Hartree energy in eV": number | undefined = undefined;
    "hartree-hertz relationship": number | undefined = undefined;
    "hartree-inverse meter relationship": number | undefined = undefined;
    "hartree-joule relationship": number | undefined = undefined;
    "hartree-kelvin relationship": number | undefined = undefined;
    "hartree-kilogram relationship": number | undefined = undefined;
    "helion-electron mass ratio": number | undefined = undefined;
    "helion mass": number | undefined = undefined;
    "helion mass energy equivalent": number | undefined = undefined;
    "helion mass energy equivalent in MeV": number | undefined = undefined;
    "helion mass in u": number | undefined = undefined;
    "helion molar mass": number | undefined = undefined;
    "helion-proton mass ratio": number | undefined = undefined;
    "hertz-atomic mass unit relationship": number | undefined = undefined;
    "hertz-electron volt relationship": number | undefined = undefined;
    "hertz-hartree relationship": number | undefined = undefined;
    "hertz-inverse meter relationship": number | undefined = undefined;
    "hertz-joule relationship": number | undefined = undefined;
    "hertz-kelvin relationship": number | undefined = undefined;
    "hertz-kilogram relationship": number | undefined = undefined;
    "inverse fine-structure constant": number | undefined = undefined;
    "inverse meter-atomic mass unit relationship": number | undefined = undefined;
    "inverse meter-electron volt relationship": number | undefined = undefined;
    "inverse meter-hartree relationship": number | undefined = undefined;
    "inverse meter-hertz relationship": number | undefined = undefined;
    "inverse meter-joule relationship": number | undefined = undefined;
    "inverse meter-kelvin relationship": number | undefined = undefined;
    "inverse meter-kilogram relationship": number | undefined = undefined;
    "inverse of conductance quantum": number | undefined = undefined;
    "Josephson constant": number | undefined = undefined;
    "joule-atomic mass unit relationship": number | undefined = undefined;
    "joule-electron volt relationship": number | undefined = undefined;
    "joule-hartree relationship": number | undefined = undefined;
    "joule-hertz relationship": number | undefined = undefined;
    "joule-inverse meter relationship": number | undefined = undefined;
    "joule-kelvin relationship": number | undefined = undefined;
    "joule-kilogram relationship": number | undefined = undefined;
    "kelvin-atomic mass unit relationship": number | undefined = undefined;
    "kelvin-electron volt relationship": number | undefined = undefined;
    "kelvin-hartree relationship": number | undefined = undefined;
    "kelvin-hertz relationship": number | undefined = undefined;
    "kelvin-inverse meter relationship": number | undefined = undefined;
    "kelvin-joule relationship": number | undefined = undefined;
    "kelvin-kilogram relationship": number | undefined = undefined;
    "kilogram-atomic mass unit relationship": number | undefined = undefined;
    "kilogram-electron volt relationship": number | undefined = undefined;
    "kilogram-hartree relationship": number | undefined = undefined;
    "kilogram-hertz relationship": number | undefined = undefined;
    "kilogram-inverse meter relationship": number | undefined = undefined;
    "kilogram-joule relationship": number | undefined = undefined;
    "kilogram-kelvin relationship": number | undefined = undefined;
    "lattice parameter of silicon": number | undefined = undefined;
    "Loschmidt constant (273.15 K, 101.325 kPa)": number | undefined = undefined;
    "mag. constant": number | undefined = undefined;
    "mag. flux quantum": number | undefined = undefined;
    "molar gas constant": number | undefined = undefined;
    "molar mass constant": number | undefined = undefined;
    "molar mass of carbon-12": number | undefined = undefined;
    "molar Planck constant": number | undefined = undefined;
    "molar Planck constant times c": number | undefined = undefined;
    "molar volume of ideal gas (273.15 K, 100 kPa)": number | undefined =
        undefined;
    "molar volume of ideal gas (273.15 K, 101.325 kPa)": number | undefined =
        undefined;
    "molar volume of silicon": number | undefined = undefined;
    "Mo x unit": number | undefined = undefined;
    "muon Compton wavelength": number | undefined = undefined;
    "muon Compton wavelength over 2 pi": number | undefined = undefined;
    "muon-electron mass ratio": number | undefined = undefined;
    "muon g factor": number | undefined = undefined;
    "muon mag. mom.": number | undefined = undefined;
    "muon mag. mom. anomaly": number | undefined = undefined;
    "muon mag. mom. to Bohr magneton ratio": number | undefined = undefined;
    "muon mag. mom. to nuclear magneton ratio": number | undefined = undefined;
    "muon mass": number | undefined = undefined;
    "muon mass energy equivalent": number | undefined = undefined;
    "muon mass energy equivalent in MeV": number | undefined = undefined;
    "muon mass in u": number | undefined = undefined;
    "muon molar mass": number | undefined = undefined;
    "muon-neutron mass ratio": number | undefined = undefined;
    "muon-proton mag. mom. ratio": number | undefined = undefined;
    "muon-proton mass ratio": number | undefined = undefined;
    "muon-tau mass ratio": number | undefined = undefined;
    "natural unit of action": number | undefined = undefined;
    "natural unit of action in eV s": number | undefined = undefined;
    "natural unit of energy": number | undefined = undefined;
    "natural unit of energy in MeV": number | undefined = undefined;
    "natural unit of length": number | undefined = undefined;
    "natural unit of mass": number | undefined = undefined;
    "natural unit of momentum": number | undefined = undefined;
    "natural unit of momentum in MeV/c": number | undefined = undefined;
    "natural unit of time": number | undefined = undefined;
    "natural unit of velocity": number | undefined = undefined;
    "neutron Compton wavelength": number | undefined = undefined;
    "neutron Compton wavelength over 2 pi": number | undefined = undefined;
    "neutron-electron mag. mom. ratio": number | undefined = undefined;
    "neutron-electron mass ratio": number | undefined = undefined;
    "neutron g factor": number | undefined = undefined;
    "neutron gyromag. ratio": number | undefined = undefined;
    "neutron gyromag. ratio over 2 pi": number | undefined = undefined;
    "neutron mag. mom.": number | undefined = undefined;
    "neutron mag. mom. to Bohr magneton ratio": number | undefined = undefined;
    "neutron mag. mom. to nuclear magneton ratio": number | undefined = undefined;
    "neutron mass": number | undefined = undefined;
    "neutron mass energy equivalent": number | undefined = undefined;
    "neutron mass energy equivalent in MeV": number | undefined = undefined;
    "neutron mass in u": number | undefined = undefined;
    "neutron molar mass": number | undefined = undefined;
    "neutron-muon mass ratio": number | undefined = undefined;
    "neutron-proton mag. mom. ratio": number | undefined = undefined;
    "neutron-proton mass ratio": number | undefined = undefined;
    "neutron-tau mass ratio": number | undefined = undefined;
    "neutron to shielded proton mag. mom. ratio": number | undefined = undefined;
    "Newtonian constant of gravitation": number | undefined = undefined;
    "Newtonian constant of gravitation over h-bar c": number | undefined =
        undefined;
    "nuclear magneton": number | undefined = undefined;
    "nuclear magneton in eV/T": number | undefined = undefined;
    "nuclear magneton in inverse meters per tesla": number | undefined =
        undefined;
    "nuclear magneton in K/T": number | undefined = undefined;
    "nuclear magneton in MHz/T": number | undefined = undefined;
    "Planck constant": number | undefined = undefined;
    "Planck constant in eV s": number | undefined = undefined;
    "Planck constant over 2 pi": number | undefined = undefined;
    "Planck constant over 2 pi in eV s": number | undefined = undefined;
    "Planck constant over 2 pi times c in MeV fm": number | undefined = undefined;
    "Planck length": number | undefined = undefined;
    "Planck mass": number | undefined = undefined;
    "Planck mass energy equivalent in GeV": number | undefined = undefined;
    "Planck temperature": number | undefined = undefined;
    "Planck time": number | undefined = undefined;
    "proton charge to mass quotient": number | undefined = undefined;
    "proton Compton wavelength": number | undefined = undefined;
    "proton Compton wavelength over 2 pi": number | undefined = undefined;
    "proton-electron mass ratio": number | undefined = undefined;
    "proton g factor": number | undefined = undefined;
    "proton gyromag. ratio": number | undefined = undefined;
    "proton gyromag. ratio over 2 pi": number | undefined = undefined;
    "proton mag. mom.": number | undefined = undefined;
    "proton mag. mom. to Bohr magneton ratio": number | undefined = undefined;
    "proton mag. mom. to nuclear magneton ratio": number | undefined = undefined;
    "proton mag. shielding correction": number | undefined = undefined;
    "proton mass": number | undefined = undefined;
    "proton mass energy equivalent": number | undefined = undefined;
    "proton mass energy equivalent in MeV": number | undefined = undefined;
    "proton mass in u": number | undefined = undefined;
    "proton molar mass": number | undefined = undefined;
    "proton-muon mass ratio": number | undefined = undefined;
    "proton-neutron mag. mom. ratio": number | undefined = undefined;
    "proton-neutron mass ratio": number | undefined = undefined;
    "proton rms charge radius": number | undefined = undefined;
    "proton-tau mass ratio": number | undefined = undefined;
    "quantum of circulation": number | undefined = undefined;
    "quantum of circulation times 2": number | undefined = undefined;
    "Rydberg constant": number | undefined = undefined;
    "Rydberg constant times c in Hz": number | undefined = undefined;
    "Rydberg constant times hc in eV": number | undefined = undefined;
    "Rydberg constant times hc in J": number | undefined = undefined;
    "Sackur-Tetrode constant (1 K, 100 kPa)": number | undefined = undefined;
    "Sackur-Tetrode constant (1 K, 101.325 kPa)": number | undefined = undefined;
    "second radiation constant": number | undefined = undefined;
    "shielded helion gyromag. ratio": number | undefined = undefined;
    "shielded helion gyromag. ratio over 2 pi": number | undefined = undefined;
    "shielded helion mag. mom.": number | undefined = undefined;
    "shielded helion mag. mom. to Bohr magneton ratio": number | undefined =
        undefined;
    "shielded helion mag. mom. to nuclear magneton ratio": number | undefined =
        undefined;
    "shielded helion to proton mag. mom. ratio": number | undefined = undefined;
    "shielded helion to shielded proton mag. mom. ratio": number | undefined =
        undefined;
    "shielded proton gyromag. ratio": number | undefined = undefined;
    "shielded proton gyromag. ratio over 2 pi": number | undefined = undefined;
    "shielded proton mag. mom.": number | undefined = undefined;
    "shielded proton mag. mom. to Bohr magneton ratio": number | undefined =
        undefined;
    "shielded proton mag. mom. to nuclear magneton ratio": number | undefined =
        undefined;
    "speed of light in vacuum": number | undefined = undefined;
    "standard acceleration of gravity": number | undefined = undefined;
    "standard atmosphere": number | undefined = undefined;
    "Stefan-Boltzmann constant": number | undefined = undefined;
    "tau Compton wavelength": number | undefined = undefined;
    "tau Compton wavelength over 2 pi": number | undefined = undefined;
    "tau-electron mass ratio": number | undefined = undefined;
    "tau mass": number | undefined = undefined;
    "tau mass energy equivalent": number | undefined = undefined;
    "tau mass energy equivalent in MeV": number | undefined = undefined;
    "tau mass in u": number | undefined = undefined;
    "tau molar mass": number | undefined = undefined;
    "tau-muon mass ratio": number | undefined = undefined;
    "tau-neutron mass ratio": number | undefined = undefined;
    "tau-proton mass ratio": number | undefined = undefined;
    "Thomson cross section": number | undefined = undefined;
    "triton-electron mag. mom. ratio": number | undefined = undefined;
    "triton-electron mass ratio": number | undefined = undefined;
    "triton g factor": number | undefined = undefined;
    "triton mag. mom.": number | undefined = undefined;
    "triton mag. mom. to Bohr magneton ratio": number | undefined = undefined;
    "triton mag. mom. to nuclear magneton ratio": number | undefined = undefined;
    "triton mass": number | undefined = undefined;
    "triton mass energy equivalent": number | undefined = undefined;
    "triton mass energy equivalent in MeV": number | undefined = undefined;
    "triton mass in u": number | undefined = undefined;
    "triton molar mass": number | undefined = undefined;
    "triton-neutron mag. mom. ratio": number | undefined = undefined;
    "triton-proton mag. mom. ratio": number | undefined = undefined;
    "triton-proton mass ratio": number | undefined = undefined;
    "unified atomic mass unit": number | undefined = undefined;
    "von Klitzing constant": number | undefined = undefined;
    "weak mixing angle": number | undefined = undefined;
    "Wien frequency displacement law constant": number | undefined = undefined;
    "Wien wavelength displacement law constant": number | undefined = undefined;
    "atomic unit of mom.um": number | undefined = undefined;
    "electron-helion mass ratio": number | undefined = undefined;
    "electron-triton mass ratio": number | undefined = undefined;
    "helion g factor": number | undefined = undefined;
    "helion mag. mom.": number | undefined = undefined;
    "helion mag. mom. to Bohr magneton ratio": number | undefined = undefined;
    "helion mag. mom. to nuclear magneton ratio": number | undefined = undefined;
    "Loschmidt constant (273.15 K, 100 kPa)": number | undefined = undefined;
    "natural unit of mom.um": number | undefined = undefined;
    "natural unit of mom.um in MeV/c": number | undefined = undefined;
    "neutron-proton mass difference": number | undefined = undefined;
    "neutron-proton mass difference energy equivalent": number | undefined =
        undefined;
    "neutron-proton mass difference energy equivalent in MeV":
        | number
        | undefined = undefined;
    "neutron-proton mass difference in u": number | undefined = undefined;
    "standard-state pressure": number | undefined = undefined;
    "alpha particle relative atomic mass": number | undefined = undefined;
    "Bohr magneton in inverse meter per tesla": number | undefined = undefined;
    "Boltzmann constant in inverse meter per kelvin": number | undefined =
        undefined;
    "conventional value of ampere-90": number | undefined = undefined;
    "conventional value of coulomb-90": number | undefined = undefined;
    "conventional value of farad-90": number | undefined = undefined;
    "conventional value of henry-90": number | undefined = undefined;
    "conventional value of ohm-90": number | undefined = undefined;
    "conventional value of volt-90": number | undefined = undefined;
    "conventional value of watt-90": number | undefined = undefined;
    "deuteron relative atomic mass": number | undefined = undefined;
    "electron gyromag. ratio in MHz/T": number | undefined = undefined;
    "electron relative atomic mass": number | undefined = undefined;
    "elementary charge over h-bar": number | undefined = undefined;
    "helion relative atomic mass": number | undefined = undefined;
    "helion shielding shift": number | undefined = undefined;
    "hyperfine transition frequency of Cs-133": number | undefined = undefined;
    "lattice spacing of ideal Si (220)": number | undefined = undefined;
    "luminous efficacy": number | undefined = undefined;
    "neutron gyromag. ratio in MHz/T": number | undefined = undefined;
    "neutron relative atomic mass": number | undefined = undefined;
    "nuclear magneton in inverse meter per tesla": number | undefined = undefined;
    "Planck constant in eV/Hz": number | undefined = undefined;
    "proton gyromag. ratio in MHz/T": number | undefined = undefined;
    "proton relative atomic mass": number | undefined = undefined;
    "reduced Compton wavelength": number | undefined = undefined;
    "reduced muon Compton wavelength": number | undefined = undefined;
    "reduced neutron Compton wavelength": number | undefined = undefined;
    "reduced Planck constant": number | undefined = undefined;
    "reduced Planck constant in eV s": number | undefined = undefined;
    "reduced Planck constant times c in MeV fm": number | undefined = undefined;
    "reduced proton Compton wavelength": number | undefined = undefined;
    "reduced tau Compton wavelength": number | undefined = undefined;
    "shielded helion gyromag. ratio in MHz/T": number | undefined = undefined;
    "shielded proton gyromag. ratio in MHz/T": number | undefined = undefined;
    "shielding difference of d and p in HD": number | undefined = undefined;
    "shielding difference of t and p in HT": number | undefined = undefined;
    "tau energy equivalent": number | undefined = undefined;
    "triton relative atomic mass": number | undefined = undefined;
    "triton to proton mag. mom. ratio": number | undefined = undefined;
    "vacuum electric permittivity": number | undefined = undefined;
    "vacuum mag. permeability": number | undefined = undefined;
    "W to Z mass ratio": number | undefined = undefined;
    constructor() {
        super();
        for (const k in Object.keys(physics)) {
            this[k] = physics[k];
        }
        this.c = physics["speed of light in vacuum"][0] as number;
        this.g = physics["standard acceleration of gravity"][0] as number;
        this.G = physics["Newtonian constant of gravitation"][0] as number;
    }
}
