export interface SlotMap {
    "snippets": {
        SnippetListPage: string,
        AddSnippetPage: string,
        SnippetList: string,
        SnippetFilter: string,
    }, 
    "math": {
        EquationDetailsModalPage: string,
        EquationsPage: string,
        EquationDetailsPage: string,
        AddEquationPage: string,
    }, 
    "editor": {
        EditorModalPage: string,
        MdxEditorPage: string,
        LatexEditorPage: string,
        EditorPage: string,
    }, 
    "UI": {
        ComponentDocsListPage: string,
        Pagination: string,
        logo: string,
        loadingIndicator: string,
        confirmationModal: string,
        ComponentDocumentationPageWrapper: string,
        AutoSettingsTable: string,
        AutoSettingFormModal: string,
        SearchResultsPage: string,
        BookmarksPage: string,
        NotesSearchResultsList: string,
        NoteSummarySearchResult: string,
        DictionaryLetterList: string,
        DictionaryPageItem: string,
        NoteTypeSecondaryFilter: string,
        NoteTypeSearchResultList: string,
        MdxNoteContainer: string,
    }, 
    "bibliography": {
        BibliographyPage: string,
        BibEntryDetails: string,
    }, 
    "taskManager": {
        TaskManagerPage: string,
        TaskDetails: string,
        AddTask: string,
        AddTaskList: string,
        TaskListSearchResultList: string,
        TaskListSearchResult: string,
    }, 
    "pdf": {
        FullPdf: string,
        EmbeddablePdf: string,
    }, 
    "navigation": {
        secondary: string,
        navbar: string,
        MultiPageSidebar: string,
        MdxNoteToc: string,
        FullScreenNavigationMenu: string,
        Footer: string,
    }, 
    "dashboard": {
        LandingPage: string,
    }, 
    "form": {
        SettingsPageContainer: string,
    }, 
    "commandPalette": {
        commandPalette: string,
    }, 
}
