import type {
    GenFileContentItem
} from "../../developmentUtilities";
import {
    DevelopmentOutput
} from "../../developmentUtilities";
import { internalAppLocations } from "../../staticAppProperties/internalLocationsAndActions";

const dev = new DevelopmentOutput();

const items: GenFileContentItem[] = [
    {
        fnc: "arrayToTypeUnion",
        props: {
            arr: internalAppLocations,
            getValue: (val) => `"${(val as { id: string }).id}"`,
            varName: "InternalAppLocationIds",
            exportVar: true
        },
    },
    {
        fnc: "arrayToTypescriptRecord",
        props: {
            arr: internalAppLocations,
            getKey: (val) => (val as {id: string}).id,
            getValue: (val) => `"${(val as {label: string}).label}"`,
            exportVar: true,
            varName: "internalAppLocationsLabelMap",
            typescriptType: "Record<InternalAppLocationIds, string>",
        },
    },
    {
        fnc: "rawPrefixContent",
        props: {
            content: "// Autogenerated from the content in packages/utilities/src/staticAppProperties/internalLocationsAndActions/main.ts\n\n"
        }
    }
];

dev.genFileContent(items, {
    filePath: "packages/utilities/src/utils/generatedUtils/internalAppLocations.ts",
    useUlldDevRootEnvVar: true
})
