import { ModeBarDefaultButtons } from "plotly.js";

// Comment out to actually display
export const plotlyRemovedButtons: ModeBarDefaultButtons[] = [
    'lasso2d',
    'select2d',
    'sendDataToCloud',
    'zoom2d',
    'pan2d',
    'zoomIn2d',
    'zoomOut2d',
    'autoScale2d',
    'resetScale2d',
    'hoverClosestCartesian',
    'hoverCompareCartesian',
    'zoom3d',
    'pan3d',
    'orbitRotation',
    'tableRotation',
    'handleDrag3d',
    'resetCameraDefault3d',
    'resetCameraLastSave3d',
    'hoverClosest3d',
    'zoomInGeo',
    'zoomOutGeo',
    'resetGeo',
    'hoverClosestGeo',
    'hoverClosestGl2d',
    'hoverClosestPie',
    'toggleHover',
    /* 'toImage', */
    'resetViews',
    'toggleSpikelines',
    'zoomInMapbox',
    'zoomOutMapbox',
    'resetViewMapbox',
    'togglespikelines',
    'togglehover',
    'hovercompare',
    'hoverclosest',
    'v1hovermode',
]

