import { z } from "zod";

export const plotlyTransitionSchema = z.object({
    duration: z.number(),
    easing: z.union([
        z.literal("linear"),
        z.literal("quad"),
        z.literal("cubic"),
        z.literal("sin"),
        z.literal("exp"),
        z.literal("circle"),
        z.literal("elastic"),
        z.literal("back"),
        z.literal("bounce"),
        z.literal("linear-in"),
        z.literal("quad-in"),
        z.literal("cubic-in"),
        z.literal("sin-in"),
        z.literal("exp-in"),
        z.literal("circle-in"),
        z.literal("elastic-in"),
        z.literal("back-in"),
        z.literal("bounce-in"),
        z.literal("linear-out"),
        z.literal("quad-out"),
        z.literal("cubic-out"),
        z.literal("sin-out"),
        z.literal("exp-out"),
        z.literal("circle-out"),
        z.literal("elastic-out"),
        z.literal("back-out"),
        z.literal("bounce-out"),
        z.literal("linear-in-out"),
        z.literal("quad-in-out"),
        z.literal("cubic-in-out"),
        z.literal("sin-in-out"),
        z.literal("exp-in-out"),
        z.literal("circle-in-out"),
        z.literal("elastic-in-out"),
        z.literal("back-in-out"),
        z.literal("bounce-in-out"),
    ]),
    ordering: z.union([
        z.literal("layout first"),
        z.literal("traces first"),
    ]).optional()
});
