import { z } from "zod";
import {
    plotlyAutoRangeOptions,
    plotlyAutoRangeSchema,
    plotlyAxisTypeSchema,
    plotlyCalendarSchema,
    plotlyCategoryOrderSchema,
    plotlyColorSchema,
    plotlyExponentFormatSchema,
    plotlyFontSchema,
    plotlyRangeModeSchema,
    plotlyShowTickPrefixSchema as plotlyShowTickPropertySchema,
    plotlySpikeModeSchema,
    plotlySpikeSnapSchema,
    plotlyTickModeSchema,
} from "../utils";
import { plotlyDataTitleObjectSchema } from "../title";
import { numberStringUnionSchema } from "../nonspecificUtilities";

export const plotlyAxisSchema = z.object({
    visible: z.boolean(),
    color: plotlyColorSchema,
    title: z.union([z.string(), plotlyDataTitleObjectSchema.partial()]),
    titlefont: plotlyFontSchema.partial(),
    type: plotlyAxisTypeSchema,
    autorange: plotlyAutoRangeSchema,
    autorangeoptions: plotlyAutoRangeOptions,
    rangemode: plotlyRangeModeSchema,
    range: z.any().array(),
    fixedrange: z.boolean(),
    tickmode: plotlyTickModeSchema,
    nticks: z.number(),
    tick0: numberStringUnionSchema,
    dtick: numberStringUnionSchema,
    tickvals: z.any().array(),
    ticktext: z.string().array(),
    ticks: z.union([z.literal("inside"), z.literal("outside"), z.literal("")]),
    mirror: z.union([
        z.literal(true),
        z.literal(false),
        z.literal("ticks"),
        z.literal("all"),
        z.literal("allticks"),
    ]),
    ticklen: z.number(),
    tickwidth: z.number(),
    tickcolor: plotlyColorSchema,
    showticklabels: z.boolean(),
    showspikes: z.boolean(),
    spikecolor: plotlyColorSchema,
    spiketickness: z.number(),
    categoryorder: plotlyCategoryOrderSchema,
    categoryarray: z.any().array(),
    tickfont: plotlyFontSchema.partial(),
    tickangle: z.literal("auto").or(z.number()),
    tickprefix: z.string(),
    showtickprefix: plotlyShowTickPropertySchema,
    ticksuffix: z.string(),
    showticksuffix: plotlyShowTickPropertySchema,
    showexponent: plotlyShowTickPropertySchema,
    exponentformat: plotlyExponentFormatSchema,
    minexponent: z.number(),
    separatethousands: z.boolean(),
    tickformat: z.string(),
    hoverformat: z.string(),
    calendar: plotlyCalendarSchema,
    // tickformatstops: TickFormatStop // handle this
    spikedash: z.string(),
    spikemode: plotlySpikeModeSchema,
    spikesnap: plotlySpikeSnapSchema,
    showline: z.boolean(),
    linecolor: plotlyColorSchema,
    linewidth: z.number(),
    showgrid: z.boolean(),
    gridcolor: plotlyColorSchema,
    gridwidth: z.number(),
    zeroline: z.boolean(),
    zerolinecolor: plotlyColorSchema,
    zerolinewidth: z.number(),
    showdividers: z.boolean(),
    dividercolor: plotlyColorSchema,
    dividerwidth: z.number(),
    autotypenumbers: z.union([z.literal("convert types"), z.literal("strict")]),
    labelalias: numberStringUnionSchema,
    maxallowed: numberStringUnionSchema,
    minallowed: numberStringUnionSchema,
});
