// Autogenerated from the content in packages/utilities/src/staticAppProperties/internalLocationsAndActions/main.ts




export type InternalAppLocationIds = "bookmarks"
    | "internalBibLink"
    | "internalNavMenuLink"
    | "internalTaskManagerLink"
    | "internalCreateToDoLink"
    | "internalSnippetsLink"
    | "internalAddSnippetLink"
    | "internalEquationsLink"
    | "internalAddEquationLink"
    | "internalDocsLink"
    | "internalComponentDocsLink"
    | "internalDictionaryLink"
    | "internalSettingsLink"
    | "internalAutoSettingsLink";


export const internalAppLocationsLabelMap: Record<InternalAppLocationIds, string> =  {
    "bookmarks": "Bookmarks",
    "internalBibLink": "Bibliography",
    "internalNavMenuLink": "Navigation",
    "internalTaskManagerLink": "Task Manager",
    "internalCreateToDoLink": "Create To Do list",
    "internalSnippetsLink": "Snippets",
    "internalAddSnippetLink": "Add Snippet",
    "internalEquationsLink": "Equations",
    "internalAddEquationLink": "Add Equation",
    "internalDocsLink": "Docs",
    "internalComponentDocsLink": "Component Docs",
    "internalDictionaryLink": "Dictionary",
    "internalSettingsLink": "Settings",
    "internalAutoSettingsLink": "Auto-Property Settings"
}