// NOTE: Autogenerated from the content in packages/state/src/actions/clientOnly/actionMap.ts

import type { ValidIconNameDynamicallyGenerated } from "@ulld/types";




export type InternalGlobalActionIds = "togglePreferFileSystem"
    | "toggleTooltips"
    | "syncRootDirectory"
    | "toggleDarkMode"
    | "toggleAllJupyterFolds"
    | "toggleIdSelectMode"
    | "showEquationIds"
    | "toggleBookmarked";


export const internalGlobalActionsIdMap: Record<InternalGlobalActionIds, {
    label: string
    defaultIcon: ValidIconNameDynamicallyGenerated
}> =  {
    "togglePreferFileSystem": {
        label: "Toggle Prefer File System",
        defaultIcon: "database-zap"
        },
    "toggleTooltips": {
        label: "Toggle Tooltips",
        defaultIcon: "popcorn"
        },
    "syncRootDirectory": {
        label: "Sync Notes",
        defaultIcon: "folder-sync"
        },
    "toggleDarkMode": {
        label: "Toggle Dark Mode",
        defaultIcon: "moon-star"
        },
    "toggleAllJupyterFolds": {
        label: "Toggle Jupyter Folds",
        defaultIcon: "origami"
        },
    "toggleIdSelectMode": {
        label: "ID Select Mode",
        defaultIcon: "box-select"
        },
    "showEquationIds": {
        label: "Show Equation Id's",
        defaultIcon: "glasses"
        },
    "toggleBookmarked": {
        label: "Toggle Bookmarked",
        defaultIcon: "bookmark"
        }
}

// NOTE: Generated as part of the build in the @ulld/utilities package.