import { z } from "zod";

export const plotTypeSchema = z.union([
    z.literal("bar"),
    z.literal("barpolar"),
    z.literal("box"),
    z.literal("candlestick"),
    z.literal("carpet"),
    z.literal("choropleth"),
    z.literal("choroplethmapbox"),
    z.literal("cone"),
    z.literal("contour"),
    z.literal("contourcarpet"),
    z.literal("densitymapbox"),
    z.literal("funnel"),
    z.literal("funnelarea"),
    z.literal("heatmap"),
    z.literal("heatmapgl"),
    z.literal("histogram"),
    z.literal("histogram2d"),
    z.literal("histogram2dcontour"),
    z.literal("image"),
    z.literal("indicator"),
    z.literal("isosurface"),
    z.literal("mesh3d"),
    z.literal("ohlc"),
    z.literal("parcats"),
    z.literal("parcoords"),
    z.literal("pie"),
    z.literal("pointcloud"),
    z.literal("sankey"),
    z.literal("scatter"),
    z.literal("scatter3d"),
    z.literal("scattercarpet"),
    z.literal("scattergeo"),
    z.literal("scattergl"),
    z.literal("scattermapbox"),
    z.literal("scatterpolar"),
    z.literal("scatterpolargl"),
    z.literal("scatterternary"),
    z.literal("splom"),
    z.literal("streamtube"),
    z.literal("sunburst"),
    z.literal("surface"),
    z.literal("table"),
    z.literal("treemap"),
    z.literal("violin"),
    z.literal("volume"),
    z.literal("waterfall"),
]);


export type PlotType = z.input<typeof plotTypeSchema>
